spring:
  application:
    name: medlab

  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: 
      highlight_sql:

  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true

  server:
    port: ${SERVER_PORT:8080}
    address: ${SERVER_ADDRESS:127.0.0.1}
